In [1]:
from constants import *
from SingleQudit import *
from SingleQuditGates import *

In [2]:
q = Qudit(3,[1, 0.5, 0.1])
print(q.get_matrix())

Length of vector r ist scaled to 1.
[[0.79365079 0.3968254  0.07936508]
 [0.3968254  0.1984127  0.03968254]
 [0.07936508 0.03968254 0.00793651]]


In [3]:
q = Qudit(4,[1, 1, 2,4])
print(q.get_matrix())

Length of vector r ist scaled to 1.
[[0.04545455 0.04545455 0.09090909 0.18181818]
 [0.04545455 0.04545455 0.09090909 0.18181818]
 [0.09090909 0.09090909 0.18181818 0.36363636]
 [0.18181818 0.18181818 0.36363636 0.72727273]]


In [4]:
q = Qudit(3,[np.sqrt(0.85355339),np.sqrt(0.14644661), 0.00001])
print(q.get_matrix())

Length of vector r ist scaled to 1.
[[8.53553390e-01 3.53553391e-01 9.23879532e-06]
 [3.53553391e-01 1.46446610e-01 3.82683433e-06]
 [9.23879532e-06 3.82683433e-06 1.00000000e-10]]


In [5]:
q._set_matrix(X_gate(q.get_matrix()))
q.get_matrix()

matrix([[1.46446610e-01+0.j, 3.53553391e-01+0.j, 3.82683433e-06+0.j],
        [3.53553391e-01+0.j, 8.53553390e-01+0.j, 9.23879532e-06+0.j],
        [3.82683433e-06+0.j, 9.23879532e-06+0.j, 1.00000000e-10+0.j]])

In [6]:
q._set_matrix(Y_gate(q.get_matrix()))
q.get_matrix()

matrix([[ 8.53553390e-01+0.00000000e+00j,
         -3.53553391e-01+0.00000000e+00j,
          0.00000000e+00-9.23879532e-06j],
        [-3.53553391e-01+0.00000000e+00j,
          1.46446610e-01+0.00000000e+00j,
          0.00000000e+00+3.82683433e-06j],
        [ 0.00000000e+00+9.23879532e-06j,
          0.00000000e+00-3.82683433e-06j,
          1.00000000e-10+0.00000000e+00j]])

In [7]:
q._set_matrix(Z_gate(q.get_matrix()))
q.get_matrix()

matrix([[8.53553390e-01+0.00000000e+00j, 3.53553391e-01+0.00000000e+00j,
         0.00000000e+00-9.23879532e-06j],
        [3.53553391e-01+0.00000000e+00j, 1.46446610e-01+0.00000000e+00j,
         0.00000000e+00-3.82683433e-06j],
        [0.00000000e+00+9.23879532e-06j, 0.00000000e+00+3.82683433e-06j,
         1.00000000e-10+0.00000000e+00j]])

In [8]:
q._set_matrix(H_gate(q.get_matrix()))
q.get_matrix()

matrix([[8.53553391e-01+0.00000000e+00j, 3.53553390e-01+0.00000000e+00j,
         0.00000000e+00-9.23879533e-06j],
        [3.53553390e-01+0.00000000e+00j, 1.46446609e-01+0.00000000e+00j,
         0.00000000e+00-3.82683432e-06j],
        [0.00000000e+00+9.23879533e-06j, 0.00000000e+00+3.82683432e-06j,
         1.00000000e-10+0.00000000e+00j]])

In [9]:
q._set_matrix(S_gate(q.get_matrix()))
q.get_matrix()

matrix([[8.53553391e-01+0.00000000e+00j, 2.16489014e-17-3.53553390e-01j,
         0.00000000e+00-9.23879533e-06j],
        [2.16489014e-17+3.53553390e-01j, 1.46446609e-01+0.00000000e+00j,
         3.82683432e-06-2.34326020e-22j],
        [0.00000000e+00+9.23879533e-06j, 3.82683432e-06+2.34326020e-22j,
         1.00000000e-10+0.00000000e+00j]])

In [10]:
q._set_matrix(T_gate(q.get_matrix()))
q.get_matrix()

matrix([[ 8.53553391e-01+0.00000000e+00j,
         -2.50000000e-01-2.50000000e-01j,
          0.00000000e+00-9.23879533e-06j],
        [-2.50000000e-01+2.50000000e-01j,
          1.46446609e-01+3.79155734e-18j,
          2.70598049e-06+2.70598049e-06j],
        [ 0.00000000e+00+9.23879533e-06j,
          2.70598049e-06-2.70598049e-06j,
          1.00000000e-10+0.00000000e+00j]])

In [11]:
q._set_matrix(amplitude_damping(q.get_matrix(), [0.025, 0.05, 0.075]))
q.get_matrix()

matrix([[ 7.89536887e-01+0.00000000e+00j,
         -2.31250000e-01-2.31250000e-01j,
          0.00000000e+00-8.88558882e-06j],
        [-2.31250000e-01+2.31250000e-01j,
          1.56801948e-01+3.50719054e-18j,
          2.60252870e-06+2.60252870e-06j],
        [ 0.00000000e+00+8.88558882e-06j,
          2.60252870e-06-2.60252870e-06j,
          5.36611653e-02+2.84366801e-19j]])

In [12]:
q._set_matrix(general_bit_flip(q.get_matrix(), 0.1))
q.get_matrix()

matrix([[ 7.15949315e-01+2.84366801e-20j,
         -2.08125000e-01-2.08124111e-01j,
          2.60252870e-07-8.25728281e-06j],
        [-2.08125000e-01+2.08124111e-01j,
          2.20075442e-01+3.15647149e-18j,
         -2.31226577e-02-2.31226577e-02j],
        [ 2.60252870e-07+8.25728281e-06j,
         -2.31226577e-02+2.31226577e-02j,
          6.39752436e-02+6.06649175e-19j]])

In [13]:
q._set_matrix(general_phase_flip(q.get_matrix(), 0.1))
q.get_matrix()

matrix([[ 7.15949315e-01+2.84366801e-20j,
         -1.94930326e-01-1.58881341e-01j,
          9.36316608e-07-6.99615183e-06j],
        [-1.94930326e-01+1.58881341e-01j,
          2.20075442e-01+3.58146162e-18j,
         -2.16567399e-02-1.76517781e-02j],
        [ 9.36316608e-07+6.99615183e-06j,
         -2.16567399e-02+1.76517781e-02j,
          6.39752436e-02+7.03842653e-19j]])

In [14]:
q._set_matrix(depolarization(q.get_matrix(), 0.1))
q.get_matrix()

matrix([[ 6.77687716e-01+2.46898179e-19j,
         -1.75437294e-01-1.42993207e-01j,
          8.42684947e-07-6.29653664e-06j],
        [-1.75437294e-01+1.42993207e-01j,
          2.31401231e-01+3.44462062e-18j,
         -1.94910659e-02-1.58866003e-02j],
        [ 8.42684947e-07+6.29653664e-06j,
         -1.94910659e-02+1.58866003e-02j,
          9.09110526e-02+8.54763555e-19j]])

In [15]:
q._set_matrix(single_Weyl_channel(q.get_matrix(), 2, 1, 0.1))
q.get_matrix()

matrix([[ 0.63305907+9.26251578e-19j, -0.15829483-1.26211580e-01j,
         -0.00361095-2.23486425e-02j],
        [-0.15829483+1.26211580e-01j,  0.21735221+3.45913476e-18j,
         -0.01754146-1.42983281e-02j],
        [-0.00361095+2.23486425e-02j, -0.01754146+1.42983281e-02j,
          0.14958872+7.93977017e-19j]])

In [16]:
q._set_matrix(general_phase_damping(q.get_matrix(), 0.1))
q.get_matrix()

matrix([[ 0.63305907+9.26251578e-19j, -0.02464983+4.59353340e-02j,
          0.0058282 +1.18925728e-04j],
        [-0.02464983-4.59353340e-02j,  0.21735221-3.65520129e-19j,
         -0.00281065+5.10476658e-03j],
        [ 0.0058282 -1.18925728e-04j, -0.00281065-5.10476658e-03j,
          0.14958872+1.65879593e-18j]])

In [17]:
q._set_matrix(physical_phase_damping(q.get_matrix(), 0.1))
q.get_matrix()

matrix([[ 0.63305907+9.26251578e-19j, -0.02230409+4.15640090e-02j,
          0.00390676+7.97182993e-05j],
        [-0.02230409-4.15640090e-02j,  0.21735221-3.65520129e-19j,
         -0.00254318+4.61898381e-03j],
        [ 0.00390676-7.97182993e-05j, -0.00254318-4.61898381e-03j,
          0.14958872+1.65879593e-18j]])

In [18]:
type(X(3))

numpy.matrix

In [19]:
X(3)

matrix([[0.+0.j, 0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j]])

In [20]:
Z(3)

matrix([[ 1. +0.j       ,  0. +0.j       ,  0. +0.j       ],
        [ 0. +0.j       , -0.5+0.8660254j,  0. +0.j       ],
        [ 0. +0.j       ,  0. +0.j       , -0.5-0.8660254j]])