In [1]:
from constants import *
from TwoQubits import *
from TwoQubitGates import *
from helper_functions_2Qubits import *

In [2]:
# define qubits q1 and q2
qq = TwoQubits([0,0,-1],[0,0,-1])

In [3]:
print(qq.coef_matrix)
print(qq.get_matrix())
#operator_sum(qq.get_matrix(),[np.matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])])
#get_rho_from_Pauli_basis(CNOTgate(qq.coef_matrix))

[[0.25 0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   1.  ]]
[[ 1.25+0.j  0.  +0.j  0.  +0.j  0.  +0.j]
 [ 0.  +0.j -0.75+0.j  0.  +0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j -0.75+0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  0.  +0.j  1.25+0.j]]


In [4]:
qq.set_Pauli_basis_matrix(X2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)
print(qq.get_matrix())

[[ 0.25  0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [-0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -1.  ]]
[[-0.75+0.j  0.  +0.j  0.  +0.j  0.  +0.j]
 [ 0.  +0.j  1.25+0.j  0.  +0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  1.25+0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  0.  +0.j -0.75+0.j]]


In [5]:
qq.set_Pauli_basis_matrix(Y2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[ 0.25  0.    0.    0.  ]
 [-0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -0.  ]
 [ 0.    0.    0.    1.  ]]


In [6]:
qq.set_Pauli_basis_matrix(Z2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[0.25 0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   1.  ]]


In [7]:
qq.set_Pauli_basis_matrix(H2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[0.25 0.   0.   0.  ]
 [0.   0.   0.   1.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]]


In [8]:
qq.set_Pauli_basis_matrix(S2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[0.25 0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   1.  ]
 [0.   0.   0.   0.  ]]


In [9]:
qq.set_Pauli_basis_matrix(T2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[ 0.25        0.          0.          0.        ]
 [ 0.          0.          0.         -0.70710678]
 [ 0.          0.          0.          0.70710678]
 [ 0.          0.          0.          0.        ]]


In [10]:
qq.set_Pauli_basis_matrix(CNOTgate(qq.coef_matrix))
print(qq.coef_matrix)

[[0.25       0.         0.         0.        ]
 [0.         0.         0.70710678 0.        ]
 [0.         0.         0.70710678 0.        ]
 [0.         0.         0.         0.        ]]


In [11]:
qq.set_Pauli_basis_matrix(CZgate(qq.coef_matrix))
print(qq.coef_matrix)

[[ 0.25        0.          0.          0.        ]
 [ 0.          0.70710678  0.          0.        ]
 [ 0.         -0.70710678  0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [12]:
qq.set_Pauli_basis_matrix(SWAPgate(qq.coef_matrix))
print(qq.coef_matrix)
print(qq.get_matrix())

[[ 0.25        0.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678  0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
[[0.25      +0.j         0.        +0.j         0.        +0.j
  0.70710678+0.70710678j]
 [0.        +0.j         0.25      +0.j         0.70710678-0.70710678j
  0.        +0.j        ]
 [0.        +0.j         0.70710678+0.70710678j 0.25      +0.j
  0.        +0.j        ]
 [0.70710678-0.70710678j 0.        +0.j         0.        +0.j
  0.25      +0.j        ]]


In [13]:
qq.set_Pauli_basis_matrix(individual_amplitude_damping(qq.coef_matrix, 0.005, 10))
print(qq.coef_matrix)
print(qq.get_matrix())#[0,0], qq.get_matrix()[1,1], qq.get_matrix()[2,2], qq.get_matrix()[3,3])

[[ 2.50000000e-01  0.00000000e+00  0.00000000e+00  6.09632194e-03]
 [ 0.00000000e+00  6.89756016e-01 -6.89756016e-01  0.00000000e+00]
 [ 0.00000000e+00  1.07763152e-04  1.07763152e-04  0.00000000e+00]
 [ 6.09632194e-03  0.00000000e+00  0.00000000e+00  6.93889390e-18]]
[[0.26219264+0.j         0.        +0.j         0.        +0.j
  0.68964825+0.68964825j]
 [0.        +0.j         0.25      +0.j         0.68986378-0.68986378j
  0.        +0.j        ]
 [0.        +0.j         0.68986378+0.68986378j 0.25      +0.j
  0.        +0.j        ]
 [0.68964825-0.68964825j 0.        +0.j         0.        +0.j
  0.23780736+0.j        ]]


In [14]:
qq.set_Pauli_basis_matrix(fully_correlated_amplitude_damping(qq.coef_matrix, 0.005, 100))
print(qq.coef_matrix)
#print(qq.get_matrix())

[[ 2.50000000e-01  0.00000000e+00  0.00000000e+00  2.45047660e-02]
 [ 0.00000000e+00  6.61941722e-01 -6.61941722e-01  0.00000000e+00]
 [ 0.00000000e+00  2.79220568e-02  2.79220568e-02  0.00000000e+00]
 [ 2.45047660e-02  0.00000000e+00  0.00000000e+00  6.93889390e-18]]


In [15]:
qq.set_Pauli_basis_matrix(individual_phase_damping(qq.coef_matrix, 0.005, 10))
print(qq.coef_matrix)

[[ 0.25        0.          0.          0.02450477]
 [ 0.          0.63006867 -0.63006867  0.        ]
 [ 0.          0.0269705   0.0269705   0.        ]
 [ 0.02450477  0.          0.          0.        ]]


In [16]:
qq.set_Pauli_basis_matrix(fully_correlated_phase_damping(qq.coef_matrix, 0.005, 100))
print(qq.coef_matrix)

[[ 2.50000000e-01  0.00000000e+00  0.00000000e+00  2.45047660e-02]
 [ 0.00000000e+00  5.62180937e-01 -5.62180937e-01  0.00000000e+00]
 [ 0.00000000e+00  9.48582327e-02  9.48582327e-02  0.00000000e+00]
 [ 2.45047660e-02  0.00000000e+00  0.00000000e+00  6.93889390e-18]]


In [17]:
qq.set_Pauli_basis_matrix(individual_phase_flip(qq.coef_matrix, 0.01))
print(qq.coef_matrix)

[[ 0.25        0.          0.          0.02450477]
 [ 0.          0.55093732 -0.55093732  0.        ]
 [ 0.          0.09296107  0.09296107  0.        ]
 [ 0.02450477  0.          0.          0.        ]]


In [18]:
qq.set_Pauli_basis_matrix(fully_correlated_phase_flip(qq.coef_matrix, 0.01))
print(qq.coef_matrix)

[[ 2.50000000e-01  0.00000000e+00  0.00000000e+00  2.45047660e-02]
 [ 0.00000000e+00  5.50937318e-01 -5.50937318e-01  0.00000000e+00]
 [ 0.00000000e+00  9.29610681e-02  9.29610681e-02  0.00000000e+00]
 [ 2.45047660e-02  0.00000000e+00  0.00000000e+00  1.38777878e-17]]
