In [1]:
from constants import *
from TwoQubits import *
from TwoQubitGates import *
from helper_functions_2Qubits import *

In [2]:
# define qubits q1 and q2
qq = TwoQubits([0,0,-1],[0,0,-1])

In [3]:
print(qq.coef_matrix)
print(qq.get_matrix())
#operator_sum(qq.get_matrix(),[np.matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])])
#get_rho_from_Pauli_basis(CNOTgate(qq.coef_matrix))

[[ 0.25  0.    0.   -0.25]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [-0.25  0.    0.    0.25]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


In [4]:
qq.set_Pauli_basis_matrix(X2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)
print(qq.get_matrix())

[[ 0.25  0.    0.   -0.25]
 [ 0.    0.    0.    0.  ]
 [-0.   -0.   -0.   -0.  ]
 [ 0.25 -0.   -0.   -0.25]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [5]:
qq.set_Pauli_basis_matrix(Y2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[ 0.25  0.    0.   -0.25]
 [-0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -0.  ]
 [-0.25  0.    0.    0.25]]


In [6]:
qq.set_Pauli_basis_matrix(Z2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[ 0.25  0.    0.   -0.25]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [-0.25  0.    0.    0.25]]


In [7]:
qq.set_Pauli_basis_matrix(H2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[ 0.25  0.    0.   -0.25]
 [-0.25  0.    0.    0.25]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]


In [8]:
qq.set_Pauli_basis_matrix(S2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[ 0.25  0.    0.   -0.25]
 [ 0.    0.    0.    0.  ]
 [-0.25  0.    0.    0.25]
 [ 0.    0.    0.    0.  ]]


In [9]:
qq.set_Pauli_basis_matrix(T2_gate(qq.coef_matrix, 1))
print(qq.coef_matrix)

[[ 0.25     +1.26831704e-18j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j -0.25     -1.26831704e-18j]
 [ 0.1767767+0.00000000e+00j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j -0.1767767+0.00000000e+00j]
 [-0.1767767+0.00000000e+00j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j  0.1767767+0.00000000e+00j]
 [ 0.       -1.26831704e-18j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j  0.       +1.26831704e-18j]]


In [10]:
qq.set_Pauli_basis_matrix(CNOTgate(qq.coef_matrix))
print(qq.coef_matrix)

[[ 0.25     +1.26831704e-18j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j  0.       +1.26831704e-18j]
 [ 0.       +0.00000000e+00j  0.1767767+0.00000000e+00j
   0.1767767+0.00000000e+00j  0.       +0.00000000e+00j]
 [ 0.       +0.00000000e+00j -0.1767767+0.00000000e+00j
   0.1767767+0.00000000e+00j  0.       +0.00000000e+00j]
 [ 0.       -1.26831704e-18j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j -0.25     -1.26831704e-18j]]


In [11]:
qq.set_Pauli_basis_matrix(CZgate(qq.coef_matrix))
print(qq.coef_matrix)

[[ 0.25     +1.26831704e-18j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j  0.       +1.26831704e-18j]
 [ 0.       +0.00000000e+00j  0.1767767+0.00000000e+00j
   0.1767767+0.00000000e+00j  0.       +0.00000000e+00j]
 [ 0.       +0.00000000e+00j -0.1767767+0.00000000e+00j
   0.1767767+0.00000000e+00j  0.       +0.00000000e+00j]
 [ 0.       -1.26831704e-18j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j -0.25     -1.26831704e-18j]]


In [12]:
qq.set_Pauli_basis_matrix(SWAPgate(qq.coef_matrix))
print(qq.coef_matrix)
#print(qq.get_matrix())

[[ 0.25     +1.26831704e-18j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j  0.       -1.26831704e-18j]
 [ 0.       +0.00000000e+00j  0.1767767+0.00000000e+00j
  -0.1767767+0.00000000e+00j  0.       +0.00000000e+00j]
 [ 0.       +0.00000000e+00j  0.1767767+0.00000000e+00j
   0.1767767+0.00000000e+00j  0.       +0.00000000e+00j]
 [ 0.       +1.26831704e-18j  0.       +0.00000000e+00j
   0.       +0.00000000e+00j -0.25     -1.26831704e-18j]]


In [13]:
qq.set_Pauli_basis_matrix(individual_amplitude_damping(qq.coef_matrix, 0.005, 10))
print(qq.coef_matrix)
print(qq.get_matrix())#[0,0], qq.get_matrix()[1,1], qq.get_matrix()[2,2], qq.get_matrix()[3,3])

[[ 0.25      +1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j  0.00609632-1.20646049e-18j]
 [ 0.        +0.00000000e+00j  0.17246594+0.00000000e+00j
  -0.17246594+0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.        +0.00000000e+00j  0.17246594+0.00000000e+00j
   0.17246594+0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.00609632+1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j -0.23780736-1.20646049e-18j]]
[[0.02438529+1.23713104e-19j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.48780736+4.94955507e-18j
  0.34493189-3.44931889e-01j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.34493189+3.44931889e-01j
  0.48780736+0.00000000e+00j 0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j 0.        +0.00000000e+00j]]


In [14]:
qq.set_Pauli_basis_matrix(fully_correlated_amplitude_damping(qq.coef_matrix, 0.005, 100))
print(qq.coef_matrix)
#print(qq.get_matrix())

[[ 0.25      +1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j  0.00609632-1.20646049e-18j]
 [ 0.        +0.00000000e+00j  0.17246594+0.00000000e+00j
  -0.17246594+0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.        +0.00000000e+00j  0.17246594+0.00000000e+00j
   0.17246594+0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.00609632+1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j -0.23780736-1.20646049e-18j]]


In [15]:
qq.set_Pauli_basis_matrix(individual_phase_damping(qq.coef_matrix, 0.005, 10))
print(qq.coef_matrix)

[[ 0.25      +1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j  0.00609632-1.20646049e-18j]
 [ 0.        +0.00000000e+00j  0.16425979+0.00000000e+00j
  -0.16425979+0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.        +0.00000000e+00j  0.16425979+0.00000000e+00j
   0.16425979+0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.00609632+1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j -0.23780736-1.20646049e-18j]]


In [16]:
qq.set_Pauli_basis_matrix(fully_correlated_phase_damping(qq.coef_matrix, 0.005, 100))
print(qq.coef_matrix)

[[ 0.25      +1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j  0.00609632-1.20646049e-18j]
 [ 0.        +0.00000000e+00j  0.16425979+0.00000000e+00j
  -0.16425979+0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.        +0.00000000e+00j  0.16425979+0.00000000e+00j
   0.16425979+0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.00609632+1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j -0.23780736-1.20646049e-18j]]


In [17]:
qq.set_Pauli_basis_matrix(individual_phase_flip(qq.coef_matrix, 0.01))
print(qq.coef_matrix)

[[ 0.25      +1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j  0.00609632-1.20646049e-18j]
 [ 0.        +0.00000000e+00j  0.1609746 +0.00000000e+00j
  -0.1609746 +0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.        +0.00000000e+00j  0.1609746 +0.00000000e+00j
   0.1609746 +0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.00609632+1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j -0.23780736-1.20646049e-18j]]


In [18]:
qq.set_Pauli_basis_matrix(fully_correlated_phase_flip(qq.coef_matrix, 0.01))
print(qq.coef_matrix)

[[ 0.25      +1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j  0.00609632-1.20646049e-18j]
 [ 0.        +0.00000000e+00j  0.1609746 +0.00000000e+00j
  -0.1609746 +0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.        +0.00000000e+00j  0.1609746 +0.00000000e+00j
   0.1609746 +0.00000000e+00j  0.        +0.00000000e+00j]
 [ 0.00609632+1.26831704e-18j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j -0.23780736-1.20646049e-18j]]
